# Generated by Django 5.2.6 on 2025-09-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='TZgXDKzTcr6NzeKK5N5mlKrCvQWmJd4q', editable=False, max_length=32, unique=True),
        ),
    ]
