# Generated by Django 5.2.6 on 2025-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='cvWZFV9kHcZ0ZSrbDfjwAsOLD4XpFTfT', editable=False, max_length=32, unique=True),
        ),
    ]
